namespace IPFilter.ListProviders
{
    using System.Collections.Generic;
    using System.Globalization;
    using Models;

    public class BlocklistMirrorProvider : IMirrorProvider {
        /// <summary>
        /// Gets a list of mirrors for this provider
        /// </summary>
        /// <returns></returns>
        public IEnumerable<FileMirror> GetMirrors()
        {
            return new[] { //new FileMirror("srzondksmjuwsvmgdbhi", "General - Anti-Infringement"),
            //new FileMirror("lakuncfhfhgiqghqxjzi", "General - Government"),
            //new FileMirror("nrylrfwkqpcnqfszvunb", "General - P2P Allow"),
            //new FileMirror("rynxmrknfjysesjtjlxy", "General - Spammers"),
            new FileMirror("dufcxgnbjsdwmwctgfuj", "General - Pedophiles"),
            //new FileMirror("chykyvyiwrfszbqynhnd", "General - Squidblacklist/US Government Blacklist"),
            //new FileMirror("tkyphgqwfqmawathcozn", "General - Squidblacklist/Prime"),
            //new FileMirror("ffxgwdvcgelinvypvhuz", "General - Squidblacklist/Malicious"),
            //new FileMirror("gzuamdjmitutrcvsmuwv", "General - Squidblacklist/Piracy Related"),
            //new FileMirror("nndhjdnpxvydcupzaann", "General - Squidblacklist/Pornography"),
            //new FileMirror("fruzekpkpzlmzozmuuhx", "General - Squidblacklist/Ads and Trackers"),
            //new FileMirror("xafnpguypyaewkmuugbd", "General - Squidblacklist/Proxies"),
            new FileMirror("ydxerpxkpcfqjaybcssw", "General - Bluetack/level1"), //bt_level1
            new FileMirror("gyisgnzbhppbvsphucsw", "General - Bluetack/level2"), //bt_level2
            new FileMirror("uwnukjqktoggdknzrhgh", "General - Bluetack/level3"),
            new FileMirror("imlmncgrkbnacgcwfjvh", "General - Bluetack/edu"),
            new FileMirror("plkehquoahljmyxjixpu", "General - Bluetack/rangetest"),
            new FileMirror("gihxqmhyunbxhbmgqrla", "General - Bluetack/bogon"), //bt_bogon
            new FileMirror("dgxtneitpuvgqqcpfulq", "General - Bluetack/ads"), //bt_ads
            new FileMirror("llvtlsjyoyiczbkjsxpf", "General - Bluetack/spyware"), //bt_spyware
            new FileMirror("xoebmbyexwuiogmbyprb", "General - Bluetack/proxy"), //bt_proxy
            new FileMirror("cwworuawihqvocglcoss", "General - Bluetack/badpeers"),
            new FileMirror("xshktygkujudfnjfioro", "General - Bluetack/Microsoft"),
            new FileMirror("mcvxsnihddgutbjfbghy", "General - Bluetack/spider"), //bt_spider
            new FileMirror("usrcshglbiilevmyfhse", "General - Bluetack/hijacked"),
            new FileMirror("xpbqleszmajjesnzddhv", "General - Bluetack/dshield"), //bt_dshield
            new FileMirror("ficutxiwawokxlcyoeye", "General - Bluetack/forumspam"),
            new FileMirror("ghlzqtqxnzctvvajwwag", "General - Bluetack/webexploit"),
            new FileMirror("bcoepfyewziejvcqyhqo", "General - Bluetack/iana-reserved"),
            new FileMirror("cslpybexmxyuacbyuvib", "General - Bluetack/iana-private"),
            new FileMirror("pwqnlynprfgtjbgqoizj", "General - Bluetack/iana-multicast"),
            new FileMirror("jhaoawihmfxgnvmaqffp", "General - Bluetack/fornonlancomputers"),
            new FileMirror("mtxmiireqmjzazcsoiem", "General - Bluetack/exclusions"),
            //new FileMirror("qlprgwgdkojunfdlzsiv", "General - Bluetack/HOSTS"),
            new FileMirror("zbdlwrqkabxbcppvrnos", "General - Spamhaus/DROP"),
            new FileMirror("ynkdjqsjyfmilsgbogqf", "General - abuse/ZeuS"),
            new FileMirror("zvjxsfuvdhoxktpeiokq", "General - abuse/SpyEye"),
            new FileMirror("erqajhwrxiuvjxqrrwfj", "General - abuse/Palevo"),
            new FileMirror("npkuuhuxcsllnhoamkvm", "General - CI Army/Malicious"),
            new FileMirror("pbqcylkejciyhmwttify", "General - malc0de/malc0de"),
            new FileMirror("zhogegszwduurnvsyhdf", "General - Yoyo/adservers"),
            new FileMirror("lujdnbasfaaixitgmxpp", "General - cidr-report/bogon"),
            new FileMirror("czvaehmjpsnwwttrdoyl", "General - CruzIT/cruzit web attacks"),
            //new FileMirror("cgbdjfsybgpgyjpqhsnd", "General - MalwareDomainList/malware domain list"),
            new FileMirror("togdoptykrlolpddwbvz", "Organizations - The Onion Router"), //tor
            new FileMirror("himxdtcxttxaaxqzgogt", "Organizations - Amazon"),
            new FileMirror("gvbjwjdedklmezhpgudg", "Organizations - Facebook"),
            new FileMirror("hkufkqvsgivyzzggrtww", "Organizations - Twitter"),
            new FileMirror("mkinfvxburnbsdijdtxk", "Organizations - CloudFlare"),
            new FileMirror("aphcqvpxuqgrkgufjruj", "Organizations - Apple"),
            new FileMirror("tgbankumtwtrzllndbmb", "Organizations - LogMeIn"), //logmein
            new FileMirror("cnxkgiklecdaihzukrud", "Organizations - Steam"),
            new FileMirror("ppqqnyihmcrryraaqsjo", "Organizations - Xfire"),
            new FileMirror("ercbntshuthyykfkmhxc", "Organizations - Blizzard"),
            new FileMirror("etmcrglomupyxtaebzht", "Organizations - Ubisoft"),
            new FileMirror("pevkykuhgaegqyayzbnr", "Organizations - Nintendo"),
            new FileMirror("gfnxlhxsijzrcuxwzebb", "Organizations - Activision"),
            new FileMirror("tukpvrvlubsputmkmiwg", "Organizations - Sony Online Entertainment"), //soe
            new FileMirror("eveiyhgmusglurfmjyag", "Organizations - Crowd Control Productions"),
            new FileMirror("qnjdimxnaupjmpqolxcv", "Organizations - Linden Lab"),
            new FileMirror("ejqebpcdmffinaetsvxj", "Organizations - Electronic Arts"),
            new FileMirror("odyaqontcydnodrlyina", "Organizations - Square Enix"),
            new FileMirror("mwjuwmebrnzyyxpbezxu", "Organizations - NCsoft"),
            new FileMirror("sdlvfabdjvrdttfjotcy", "Organizations - Riot Games"),
            new FileMirror("zvwwndvzulqcltsicwdg", "Organizations - PunkBuster"),
            new FileMirror("alxugfmeszbhpxqfdits", "Organizations - Joost"),
            new FileMirror("aevzidimyvwybzkletsg", "Organizations - Pandora"),
            new FileMirror("nzldzlpkgrcncdomnttb", "Organizations - The Pirate Bay"),
            new FileMirror("toboaiysofkflwgrttmb", "ISP - AOL"),
            new FileMirror("rsgyxvuklicibautguia", "ISP - Comcast"), //comcast
            new FileMirror("dwwbsmzirrykdlvpqozb", "ISP - Cablevision"), //cablevision
            new FileMirror("cdmdbprvldivlqsaqjol", "ISP - Verizon"),
            new FileMirror("grbtkzijgrowvobvessf", "ISP - AT&T"),
            new FileMirror("nlgdvmvfxvoimdunmuju", "ISP - Cox Communications"),
            new FileMirror("aqtsnttnqmcucwrjmohd", "ISP - Time Warner Cable"),
            new FileMirror("htnzojgossawhpkbulqw", "ISP - Charter"),
            new FileMirror("twdblifaysaqtypevvdp", "ISP - Embarq"),
            new FileMirror("psaoblrwylfrdsspfuiq", "ISP - Suddenlink"),
            new FileMirror("hngtqrhhuadlceqxbrob", "ISP - Sprint"),
            new FileMirror("ad", "Country - Andorra"),
            new FileMirror("ae", "Country - United Arab Emirates"),
            new FileMirror("af", "Country - Afghanistan"),
            new FileMirror("ag", "Country - Antigua and Barbuda"),
            new FileMirror("ai", "Country - Anguilla"),
            new FileMirror("al", "Country - Albania"),
            new FileMirror("am", "Country - Armenia"),
            new FileMirror("an", "Country - Netherlands Antilles"),
            new FileMirror("ao", "Country - Angola"),
            new FileMirror("ap", "Country - Non-spec Asia Pas Location"),
            new FileMirror("ar", "Country - Argentina"),
            new FileMirror("as", "Country - American Samoa"),
            new FileMirror("at", "Country - Austria"),
            new FileMirror("au", "Country - Australia"),
            new FileMirror("aw", "Country - Aruba"),
            new FileMirror("ax", "Country - Aland Islands"),
            new FileMirror("az", "Country - Azerbaijan"),
            new FileMirror("ba", "Country - Bosnia and Herzegowina"),
            new FileMirror("bb", "Country - Barbados"),
            new FileMirror("bd", "Country - Bangladesh"),
            new FileMirror("be", "Country - Belgium"),
            new FileMirror("bf", "Country - Burkina Faso"),
            new FileMirror("bg", "Country - Bulgaria"),
            new FileMirror("bh", "Country - Bahrain"),
            new FileMirror("bi", "Country - Burundi"),
            new FileMirror("bj", "Country - Benin"),
            new FileMirror("bm", "Country - Bermuda"),
            new FileMirror("bn", "Country - Brunei Darussalam"),
            new FileMirror("bo", "Country - Bolivia"),
            new FileMirror("br", "Country - Brazil"),
            new FileMirror("bs", "Country - Bahamas"),
            new FileMirror("bt", "Country - Bhutan"),
            new FileMirror("bw", "Country - Botswana"),
            new FileMirror("by", "Country - Belarus"),
            new FileMirror("bz", "Country - Belize"),
            new FileMirror("ca", "Country - Canada"),
            new FileMirror("cd", "Country - The Democratic Republic of The Congo"),
            new FileMirror("cf", "Country - Central African Republic"),
            new FileMirror("cg", "Country - Congo"),
            new FileMirror("ch", "Country - Switzerland"),
            new FileMirror("ci", "Country - Cote D'ivoire"),
            new FileMirror("ck", "Country - Cook Islands"),
            new FileMirror("cl", "Country - Chile"),
            new FileMirror("cm", "Country - Cameroon"),
            new FileMirror("cn", "Country - China"),
            new FileMirror("co", "Country - Colombia"),
            new FileMirror("cr", "Country - Costa Rica"),
            new FileMirror("cs", "Country - Serbia and Montenegro"),
            new FileMirror("cu", "Country - Cuba"),
            new FileMirror("cv", "Country - Cape Verde"),
            new FileMirror("cy", "Country - Cyprus"),
            new FileMirror("cz", "Country - Czech Republic"),
            new FileMirror("de", "Country - Germany"),
            new FileMirror("dj", "Country - Djibouti"),
            new FileMirror("dk", "Country - Denmark"),
            new FileMirror("do", "Country - Dominican Republic"),
            new FileMirror("dz", "Country - Algeria"),
            new FileMirror("ec", "Country - Ecuador"),
            new FileMirror("ee", "Country - Estonia"),
            new FileMirror("eg", "Country - Egypt"),
            new FileMirror("er", "Country - Eritrea"),
            new FileMirror("es", "Country - Spain"),
            new FileMirror("et", "Country - Ethiopia"),
            new FileMirror("eu", "Country - European Union"),
            new FileMirror("fi", "Country - Finland"),
            new FileMirror("fj", "Country - Fiji"),
            new FileMirror("fm", "Country - Federated States of Micronesia"),
            new FileMirror("fo", "Country - Faroe Islands"),
            new FileMirror("fr", "Country - France"),
            new FileMirror("ga", "Country - Gabon"),
            new FileMirror("gb", "Country - United Kingdom"),
            new FileMirror("gd", "Country - Grenada"),
            new FileMirror("ge", "Country - Georgia"),
            new FileMirror("gf", "Country - French Guiana"),
            new FileMirror("gg", "Country - Guernsey"),
            new FileMirror("gh", "Country - Ghana"),
            new FileMirror("gi", "Country - Gibraltar"),
            new FileMirror("gl", "Country - Greenland"),
            new FileMirror("gm", "Country - Gambia"),
            new FileMirror("gn", "Country - Guinea"),
            new FileMirror("gp", "Country - Guadeloupe"),
            new FileMirror("gq", "Country - Equatorial Guinea"),
            new FileMirror("gr", "Country - Greece"),
            new FileMirror("gt", "Country - Guatemala"),
            new FileMirror("gu", "Country - Guam"),
            new FileMirror("gw", "Country - Guinea-bissau"),
            new FileMirror("gy", "Country - Guyana"),
            new FileMirror("hk", "Country - Hong Kong"),
            new FileMirror("hn", "Country - Honduras"),
            new FileMirror("hr", "Country - Croatia"),
            new FileMirror("ht", "Country - Haiti"),
            new FileMirror("hu", "Country - Hungary"),
            new FileMirror("id", "Country - Indonesia"),
            new FileMirror("ie", "Country - Ireland"),
            new FileMirror("il", "Country - Israel"),
            new FileMirror("im", "Country - Isle of Man"),
            new FileMirror("in", "Country - India"),
            new FileMirror("io", "Country - British Indian Ocean Territory"),
            new FileMirror("iq", "Country - Iraq"),
            new FileMirror("ir", "Country - Iran"),
            new FileMirror("is", "Country - Iceland"),
            new FileMirror("it", "Country - Italy"),
            new FileMirror("je", "Country - Jersey"),
            new FileMirror("jm", "Country - Jamaica"),
            new FileMirror("jo", "Country - Jordan"),
            new FileMirror("jp", "Country - Japan"),
            new FileMirror("ke", "Country - Kenya"),
            new FileMirror("kg", "Country - Kyrgyzstan"),
            new FileMirror("kh", "Country - Cambodia"),
            new FileMirror("ki", "Country - Kiribati"),
            new FileMirror("kn", "Country - Saint Kitts and Nevis"),
            new FileMirror("kp", "Country - Democratic People's Republic of Korea"),
            new FileMirror("kr", "Country - Republic of Korea"),
            new FileMirror("kw", "Country - Kuwait"),
            new FileMirror("ky", "Country - Cayman Islands"),
            new FileMirror("kz", "Country - Kazakhstan"),
            new FileMirror("la", "Country - Lao People's Democratic Republic"),
            new FileMirror("lb", "Country - Lebanon"),
            new FileMirror("lc", "Country - Saint Lucia"),
            new FileMirror("li", "Country - Liechtenstein"),
            new FileMirror("lk", "Country - Sri Lanka"),
            new FileMirror("lr", "Country - Liberia"),
            new FileMirror("ls", "Country - Lesotho"),
            new FileMirror("lt", "Country - Lithuania"),
            new FileMirror("lu", "Country - Luxembourg"),
            new FileMirror("lv", "Country - Latvia"),
            new FileMirror("ly", "Country - Libyan Arab Jamahiriya"),
            new FileMirror("ma", "Country - Morocco"),
            new FileMirror("mc", "Country - Monaco"),
            new FileMirror("md", "Country - Moldova Republic of"),
            new FileMirror("me", "Country - Montenegro"),
            new FileMirror("mf", "Country - Saint Martin"),
            new FileMirror("mg", "Country - Madagascar"),
            new FileMirror("mh", "Country - Marshall Islands"),
            new FileMirror("mk", "Country - Macedonia"),
            new FileMirror("ml", "Country - Mali"),
            new FileMirror("mm", "Country - Myanmar"),
            new FileMirror("mn", "Country - Mongolia"),
            new FileMirror("mo", "Country - Macau"),
            new FileMirror("mp", "Country - Northern Mariana Islands"),
            new FileMirror("mr", "Country - Mauritania"),
            new FileMirror("ms", "Country - Montserrat"),
            new FileMirror("mt", "Country - Malta"),
            new FileMirror("mu", "Country - Mauritius"),
            new FileMirror("mv", "Country - Maldives"),
            new FileMirror("mw", "Country - Malawi"),
            new FileMirror("mx", "Country - Mexico"),
            new FileMirror("my", "Country - Malaysia"),
            new FileMirror("mz", "Country - Mozambique"),
            new FileMirror("na", "Country - Namibia"),
            new FileMirror("nc", "Country - New Caledonia"),
            new FileMirror("ne", "Country - Niger"),
            new FileMirror("nf", "Country - Norfolk Island"),
            new FileMirror("ng", "Country - Nigeria"),
            new FileMirror("ni", "Country - Nicaragua"),
            new FileMirror("nl", "Country - Netherlands"),
            new FileMirror("no", "Country - Norway"),
            new FileMirror("np", "Country - Nepal"),
            new FileMirror("nr", "Country - Nauru"),
            new FileMirror("nu", "Country - Niue"),
            new FileMirror("nz", "Country - New Zealand"),
            new FileMirror("om", "Country - Oman"),
            new FileMirror("pa", "Country - Panama"),
            new FileMirror("pe", "Country - Peru"),
            new FileMirror("pf", "Country - French Polynesia"),
            new FileMirror("pg", "Country - Papua New Guinea"),
            new FileMirror("ph", "Country - Philippines"),
            new FileMirror("pk", "Country - Pakistan"),
            new FileMirror("pl", "Country - Poland"),
            new FileMirror("pm", "Country - St. Pierre and Miquelon"),
            new FileMirror("pr", "Country - Puerto Rico"),
            new FileMirror("ps", "Country - Palestinian Territory Occupied"),
            new FileMirror("pt", "Country - Portugal"),
            new FileMirror("pw", "Country - Palau"),
            new FileMirror("py", "Country - Paraguay"),
            new FileMirror("qa", "Country - Qatar"),
            new FileMirror("re", "Country - Reunion"),
            new FileMirror("ro", "Country - Romania"),
            new FileMirror("rs", "Country - Serbia"),
            new FileMirror("ru", "Country - Russia"),
            new FileMirror("rw", "Country - Rwanda"),
            new FileMirror("sa", "Country - Saudi Arabia"),
            new FileMirror("sb", "Country - Solomon Islands"),
            new FileMirror("sc", "Country - Seychelles"),
            new FileMirror("sd", "Country - Sudan"),
            new FileMirror("se", "Country - Sweden"),
            new FileMirror("sg", "Country - Singapore"),
            new FileMirror("si", "Country - Slovenia"),
            new FileMirror("sk", "Country - Slovakia (SLOVAK Republic)"),
            new FileMirror("sl", "Country - Sierra Leone"),
            new FileMirror("sm", "Country - San Marino"),
            new FileMirror("sn", "Country - Senegal"),
            new FileMirror("sr", "Country - Suriname"),
            new FileMirror("sv", "Country - El Salvador"),
            new FileMirror("sy", "Country - Syrian Arab Republic"),
            new FileMirror("sz", "Country - Swaziland"),
            new FileMirror("tc", "Country - Turks and Caicos Islands"),
            new FileMirror("tg", "Country - Togo"),
            new FileMirror("th", "Country - Thailand"),
            new FileMirror("tj", "Country - Tajikistan"),
            new FileMirror("tl", "Country - Timor-leste"),
            new FileMirror("tm", "Country - Turkmenistan"),
            new FileMirror("tn", "Country - Tunisia"),
            new FileMirror("to", "Country - Tonga"),
            new FileMirror("tr", "Country - Turkey"),
            new FileMirror("tt", "Country - Trinidad and Tobago"),
            new FileMirror("tv", "Country - Tuvalu"),
            new FileMirror("tw", "Country - Taiwan"),
            new FileMirror("tz", "Country - Tanzania United Republic of"),
            new FileMirror("ua", "Country - Ukraine"),
            new FileMirror("ug", "Country - Uganda"),
            new FileMirror("us", "Country - United States"),
            new FileMirror("uy", "Country - Uruguay"),
            new FileMirror("uz", "Country - Uzbekistan"),
            new FileMirror("va", "Country - Holy See (VATICAN City State)"),
            new FileMirror("vc", "Country - Saint Vincent and The Grenadines"),
            new FileMirror("ve", "Country - Venezuela"),
            new FileMirror("vg", "Country - Virgin Islands (BRITISH)"),
            new FileMirror("vi", "Country - Virgin Islands (U.S.)"),
            new FileMirror("vn", "Country - Vietnam"),
            new FileMirror("vu", "Country - Vanuatu"),
            new FileMirror("wf", "Country - Wallis and Futuna Islands"),
            new FileMirror("ws", "Country - Samoa"),
            new FileMirror("ye", "Country - Yemen"),
            new FileMirror("za", "Country - South Africa"),
            new FileMirror("zm", "Country - Zambia"),
            new FileMirror("zw", "Country - Zimbabwe"),
            new FileMirror("bimsvyvtgxeelunveyal", "Other - bluetack/webexploit-forumspam"),
            new FileMirror("dhuwlruzmglnfaneeizx", "Other - dchubad/faker"), //dcha_faker
            new FileMirror("qpuabqfzsykfvglktzkh", "Other - dchubad/hacker"),
            new FileMirror("zchgtvitlwnwcjfuxovf", "Other - dchubad/pedophiles"), //dcha_pedophiles
            new FileMirror("falwwczjguruglzisxdr", "Other - dchubad/spammer"),
            new FileMirror("zfucwtjkfwkalytktyiw", "Other - peerblock/rapidshare"),
            new FileMirror("ewqglwibdgjttwttrinl", "Other - tbg/bogon"),
            new FileMirror("jcjfaxgyyshvdbceroxf", "Other - tbg/business-isps"),
            new FileMirror("lljggjrpmefcwqknpalp", "Other - tbg/educational-institutions"),
            new FileMirror("ecqbsykllnadihkdirsh", "Other - tbg/general-corporate-ranges"),
            new FileMirror("tbnuqfclfkemqivekikv", "Other - tbg/hijacked"),
            new FileMirror("ijfqtofzixtwayqovmxn", "Other - tbg/primary-threats"),
            new FileMirror("pfefqteoxlfzopecdtyw", "Other - tbg/search-engines")};
        }

        /// <summary>
        /// The name of the mirror provider
        /// </summary>
        public string Name { get { return "I-BlockList"; } }

        public string GetUrlForMirror(FileMirror mirror)
        {
            return string.Format(CultureInfo.CurrentCulture, "http://list.iblocklist.com/?fileformat=dat&archiveformat=gz&list={0}", mirror.Id);
        }

        public override string ToString()
        {
            return Name;
        }
    }
}
