name: 'Build & release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        type: string

  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: windows-latest
    env:
      VERSION: ${{inputs.version || github.ref_name}}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Restore
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "/t:Restore" "/p:Configuration=Release" "/p:Version=$env:VERSION"

      - name: Build
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "/p:Configuration=Release" "/p:Version=$env:VERSION"

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create $env:VERSION --draft --prerelease --title "v$env:VERSION" --notes "Download and run **IPFilter.msi** to install. If you wish to just download and run the self-contained executable, you can download IPFilter.exe" ./Bin/IPFilter.msi ./Bin/IPFilter.exe
